config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/manage_users' => 'users#all', as: 'users'
  post '/manage_users/:id' => 'users#delete', as: 'delete_user'


  resources :events, path: '/' do
    resources :tracks
    resources :sessions do
      post 'approve', on: :member
      post 'revoke', on: :member
      get 'grid', on: :collection
    end
    resources :users, except: [:delete], path: :presenters do
      get 'master', on: :collection
    end
    resources :pages
    resources :rooms
    resources :slots
    get 'archive', on: :member
    get 'unarchive', on: :member
  end

  root to: 'events#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :track
  belongs_to :room
end

app/models/event.rb
class Event < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  has_rich_text :description
  has_many :pages
  has_many :rooms
  has_many :slots
  has_many :sessions
  has_many :users, through: :sessions
  has_many :tracks

  def unschedule!
    sessions.each do |s|
      s.slots = []
      s.rooms = []
      s.save
    end
  end
end

app/models/page.rb
class Page < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  has_rich_text :content
  belongs_to :event

  scope :publishable, -> { where("title NOT LIKE '_%'") }

  def should_generate_new_friendly_id?
   title_changed?
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_rich_text :description
  belongs_to :event
  has_many :assignments
  has_many :tracks, through: :assignments
  has_and_belongs_to_many :sessions
end

app/models/rooms_sessions.rb
class RoomsSessions < ApplicationRecord
  belongs_to :session
  belongs_to :room
end

app/models/session.rb
class Session < ApplicationRecord
  has_rich_text :description
  has_rich_text :organizer_notes
  has_rich_text :links
  belongs_to :event
  has_and_belongs_to_many :slots
  has_and_belongs_to_many :rooms
  has_and_belongs_to_many :users
  has_many :taggings, dependent: :destroy
  has_many :tracks, through: :taggings

  def to_presenter_info
    "#{title} - #{slots.map(&:name).join('/')} - #{rooms.map(&:name).join('/')}"
  end

  def live?
    approved && slots.any?(&:happening?) && rooms.present?
  end
end

app/models/sessions_slots.rb
class SessionsSlots < ApplicationRecord
  belongs_to :session
  belongs_to :slot
end

app/models/sessions_users.rb
class SessionsUsers < ApplicationRecord
  belongs_to :session
  belongs_to :user
end

app/models/slot.rb
class Slot < ApplicationRecord
  belongs_to :event
  has_and_belongs_to_many :sessions

  def name
    r = ''
    r << starts_at.strftime('%b %e, %l:%M %p - ')
    if starts_at.to_date == ends_at.to_date
      r << ends_at.strftime('%l:%M %p')
    else
      r << ends_at.strftime('%b %e, %l:%M %p - ')
    end
    r
  end

  def happening?
    starts_at <= Time.now && ends_at >= Time.now
  end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :track
  belongs_to :session
end

app/models/track.rb
class Track < ApplicationRecord
  extend FriendlyId
  friendly_id :label, use: :slugged
  has_many :taggings
  has_many :sessions, through: :taggings
  has_many :assignments
  has_many :rooms, through: :assignments
  belongs_to :event
  has_rich_text :description
end

app/models/user.rb
class User < ApplicationRecord
  has_rich_text :profile
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_and_belongs_to_many :sessions

  def admin?
    administrator
  end

  alias :admin :admin?

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_event, except: [:all, :delete]
  before_action :set_user, only: [:show, :edit, :update]
  before_action :check_for_admin, except: [:index, :show]
  
  def index
    @users = @event.users.order(:last_name, :first_name).uniq.keep_if { |u| u.sessions.where(approved: true).count > 0 }
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to event_users_path(@event), notice: 'Created presenter'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    if @user.update(user_params)
      redirect_to event_users_path(@event), notice: 'Updated presenter'
    else
      render :edit
    end
  end

  def master
    @users = @event.users.order(:last_name, :first_name).uniq
    render layout: 'full'
  end

  def all
    @users = User.all
  end

  def delete
    @user = User.find(params[:id])
    @user.delete
    redirect_to users_path
  end

  private

  def set_user
    @user = @event.users.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :profile)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}", role: "alert") do
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message
            end)
    end
    nil
  end

  def contrasting_color color
    base = Color::RGB.by_hex(color)
    if base.brightness > 0.5
      '#000'
    else
      '#fff'
    end
  end

  def track_badge(track)
    %Q{<span class="badge" style="background-color: #{track.color}; color: #{contrasting_color(track.color)};">#{track.label}</span>}.html_safe
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/presenters_helper.rb
module PresentersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/users/_form.html.erb
<%= form_with(model: [@event, presenter], local: true) do |f| %>
  <% if presenter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(presenter.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% presenter.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <h2>Account Details</h2>
        </div>
        <div class="card-body">
          <div class="form-row">
            <div class="col">
              <%= f.label :email %>
            </div>
            <div class="col">
              <%= f.email_field :email, autofocus: true, autocomplete: 'email', class: 'form-control' %>
            </div>
          </div>
          <div class="form-row">
            <div class="col">
              <%= f.label :first_name %>
            </div>
            <div class="col">
              <%= f.text_field :first_name, autocomplete: 'given-name', class: 'form-control' %>
            </div>
          </div>
          <div class="form-row">
            <div class="col">
              <%= f.label :last_name %>
            </div>
            <div class="col">
              <%= f.text_field :last_name, autocomplete: 'family-name', class: 'form-control' %>
            </div>
          </div>
          <% if current_user.admin? %>
            <div class="form-row">
              <div class="col">
                <%= f.label :admin %>
              </div>
              <div class="col">
                <%= f.select :admin, [true, false], class: 'form-control' %>
              </div>
            </div>
          <% end %>

          <% if presenter.persisted? %>
            <div class="form-row">
              <p>Want to change your password?</p>
            </div>
            <div class="form-row">
              <div class="col">
                <%= f.label :password %>
              </div>
              <div class="col">
                <%= f.password_field :password, autocomplete: 'new-password', class: 'form-control' %>
              </div>
            </div>
            <div class="form-row">
              <div class="col">
                <%= f.label :password_confirmation %>
              </div>
              <div class="col">
                <%= f.password_field :password_confirmation, autocomplete: 'new-password', class: 'form-control' %>
              </div>
            </div>
            <div class="form-row mt-4">
              <p>Enter your current password to confirm your changes.</p>
            </div>
            <div class="form-row">
              <div class="col">
                <%= f.label :current_password %>
              </div>
              <div class="col">
                <%= f.password_field :current_password, autocomplete: 'password', class: 'form-control' %>
              </div>
            </div>
          <% else %>
            <div class="form-row">
              <div class="col">
                <%= f.label :password %>
              </div>
              <div class="col">
                <%= f.password_field :password, autocomplete: 'new-password', class: 'form-control' %>
              </div>
            </div>

            <div class="form-row">
              <div class="col">
                <%= f.label :password_confirmation %>
              </div>
              <div class="col">
                <%= f.password_field :password_confirmation, autocomplete: 'password', class: 'form-control' %>
              </div>
            </div>
          <% end %>
          <div class="form-row mt-4">
            <div class="col-8 mx-auto">
              <%= f.submit 'Save', class: 'btn btn-block btn-success' %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <h2>Your Profile</h2>
        </div>
        <div class="card-body">
          <p class="small">
            If you're a presenter, this will be displayed along with any sessions you're assigned to! 
          </p>
          <%= f.rich_text_area :profile %>
        </div>
      </div>
    </div>
  </div>


<% end %>

app/views/users/all.html.erb
<h1>All Users</h1>

<div class="card">
  <div class="card-body">
    <% @users.each do |user| %>
      <div class="row mb-4 align-items-center">
        <div class="col">
        <%= user.first_name %> <%= user.last_name %>
        </div>
        <div class="col">
          <%= user.email %>
        </div>
        <div class="col">
          <%= button_to 'Delete', delete_user_path(user), method: 'DELETE', class: 'btn btn-danger' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<%= render partial: 'form', locals: {presenter: @user} %>

app/views/users/index.html.erb
<h1><%= @event.name %> Presenters</h1>

<% if admin? ||@event.pages.where(title: '_presenters').first.content.present? %>
  <div class="card mb-5">
    <div class="card-body">
      <% if p = @event.pages.where(title: '_presenters').first %>
        <%= p.content %>
      <% end %>
    </div>
    <% if admin? %>
      <div class="card-footer">
        <% if p = @event.pages.where(title: '_presenters').first %>
          <%= link_to 'Edit Content Page', edit_event_page_path(@event, p), class: 'btn btn-warning' %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

<div class="card">
  <div class="card-body">
    <% @users.each do |user| %>
      <div class="row mb-4 align-items-center">
        <div class="col">
          <%= link_to "#{user.first_name} #{user.last_name}", event_user_path(@event, user) %>
        </div>
        <div class="col">
          <% user.sessions.where(event: @event, approved: true).each do |session| %>
            <div>
              <%= link_to session.title, [@event, session] %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/master.html.erb
<table>
  <tbody>
    <% last = nil %>
    <% @users.each do |user| %>
      <% user.sessions.where(event: @event, approved: true).each do |session| %>
        <tr>
          <td>
            <%= "#{user.first_name} #{user.last_name}" if last != user %>
          </td>
          <td>
            <%= user.email if last != user %>
          </td>
          <td>
            <%= session.title %>
          </td>
          <td>
            <%= session.rooms.map(&:name).join(', ') %>
          </td>
          <td>
            <%= session.slots.map(&:name).join(', ') %>
          </td>
          <% last = user %>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<%= render partial: 'form', locals: {presenter: @user} %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<div class="row">
  <div class="col-md-4">
    <div class="card">
      <div class="card-body">
        <%= @user.profile %>
      </div>
      <% if admin? %>
        <div class="card-footer d-flex justify-content-between">
          <%= link_to 'Edit Presenter', edit_event_user_path(@event, @user), class: 'btn btn-warning' %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-md-8">
    <div class="card">
      <div class="card-body">
        <% @user.sessions.where(event: @event, approved: true).each do |session| %>
          <div class="row align-items-center mb-2">
            <div class="col">
              <%= link_to session.title, [@event, session] %>
            </div>
            <% if @event.scheduled %>
              <div class="col">
                <% session.rooms.each do |room| %>
                  <div>
                    <%= link_to room.name, [@event, room] %>
                  </div>
                <% end %>
                <% session.slots.each do |slot| %>
                  <div>
                    <%= link_to slot.name, [@event, slot] %>
                  </div>
                <% end %>
              </div>
          <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>