config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/manage_users' => 'users#all', as: 'users'
  post '/manage_users/:id' => 'users#delete', as: 'delete_user'


  resources :events, path: '/' do
    resources :tracks
    resources :sessions do
      post 'approve', on: :member
      post 'revoke', on: :member
      get 'grid', on: :collection
    end
    resources :users, except: [:delete], path: :presenters do
      get 'master', on: :collection
    end
    resources :pages
    resources :rooms
    resources :slots
    get 'archive', on: :member
    get 'unarchive', on: :member
  end

  root to: 'events#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  has_rich_text :description
  has_many :pages
  has_many :rooms
  has_many :slots
  has_many :sessions
  has_many :users, through: :sessions
  has_many :tracks

  def unschedule!
    sessions.each do |s|
      s.slots = []
      s.rooms = []
      s.save
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :archive, :unarchive]
  before_action :check_for_admin, except: [:index, :show, :archive, :unarchive]

  # GET /events
  # GET /events.json
  def index
    @events = params[:archived] ? Event.where(archived: true).order(:created_at) : Event.where(archived: false).order(:created_at)
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        @event.pages.create(title: '_presenters')
        @event.pages.create(title: '_rooms')
        @event.pages.create(title: '_slots')
        @event.pages.create(title: '_sessions')
        @event.pages.create(title: '_tracks')
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def archive
    @event.archived = true
    @event.save
    redirect_to root_path
  end

  def unarchive
    @event.archived = false
    @event.save
    redirect_to @event
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :slug, :description, :open, :published, :scheduled, :shared)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card">
    <div class="card-body">
      <div class="row mb-3">
        <div class="col-2">
          <%= form.label :name %>
        </div>
        <div class="col-6">
          <%= form.text_field :name, class: 'form-control' %>
        </div>
        <div class="col-2">
          <%= form.label :slug, 'URL Slug' %>
        </div>
        <div class="col-2">
          <%= form.text_field :slug, class: 'form-control' %>
        </div>
      </div>

      <div class="row mb-3">
        <div class="col-2">
          <%= form.label :open, 'Submissions Open' %>
        </div>
        <div class="col-1">
          <%= form.check_box :open %>
        </div>
        <div class="col-2">
          <%= form.label :open, 'Publish Information' %>
        </div>
        <div class="col-1">
          <%= form.check_box :published %>
        </div>
        <div class="col-2">
          <%= form.label :open, 'Publish Schedule' %>
        </div>
        <div class="col-1">
          <%= form.check_box :scheduled %>
        </div>
        <div class="col-2">
          <%= form.label :shared, 'Share Links' %>
        </div>
        <div class="col-1">
          <%= form.check_box :shared %>
        </div>

      </div>

    <%= form.rich_text_area :description %>

  <div class="actions mt-3">
    <%= form.submit nil, class: 'btn btn-primary' %>
  </div>
    </div>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<p class="mt-5">
  <% if @event.archived %>
    <%= link_to "Un-archive this Event", unarchive_event_path(@event), class: 'text-info'%>
  <% else %>
    <%= link_to "Archive this Event", archive_event_path(@event), class: 'text-danger'%>
  <% end %>
</p>

app/views/events/index.html.erb
<h1>Events</h1>

<% @events.each do |event| %>
  <div class="card mb-4">
    <div class="card-body">
      <%= link_to event do %>
        <h2><%= event.name %></h2>
      <% end %>
      <%= event.description %>
    </div>
  </div>
<% end %>
<% if admin? %>
  <br><br>
  <%= link_to 'New Event', new_event_path %>
<% end %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>

<div class="row">
  <div class="col-md-3">
    <div class="card">
      <div class="card-body">
        <% if @event.open %>
          <p>This event is currently accepting session proposals!</p>

          <p>
            <% if current_user %>
              <%= link_to 'Submit a New Proposal', new_event_session_path(@event) %> or <%= link_to 'View and Manage Proposals', event_sessions_path(@event) %>
            <% else %>
              <%= link_to 'Sign In', new_user_session_path %> or <%= link_to 'Create an Account', new_user_registration_path %> to submit a proposal!
            <% end %>
          </p>
        <% end %>
        <% if @event.scheduled || @event.published || admin? %>
          <div class="d-flex-column text-center">
            <% if @event.scheduled || admin?  %>
              <div class="mb-3">
                <%= link_to event_rooms_path(@event) do %>
                  <div class="huge">
                    <%= @event.rooms.count %>
                  </div>
                  <div>
                    <i class="fas fa-door-open"></i> <%= @event.rooms.count == 1 ? 'Room' : 'Rooms' %>
                  </div>
                <% end %>
              </div>
              <div class="mb-3">
                <%= link_to event_slots_path(@event) do %>
                  <div class="huge">
                    <%= @event.slots.count %>
                  </div>
                  <div>
                    <i class="fas fa-clock"></i> <%= @event.slots.count == 1 ? 'Slot' : 'Slots' %>
                  </div>
                <% end %>
              </div>
            <% end %>
            <div class="mb-3">
              <%= link_to event_users_path(@event) do %>
                <div class="huge">
                  <%= @event.users.uniq.count %>
                </div>
                <div>
                  <i class="fas fa-user"></i> <%= @event.users.uniq.count == 1 ? 'Presenter' : 'Presenters' %>
                </div>
              <% end %>
            </div>
            <div class="mb-3">
              <%= link_to event_tracks_path(@event) do %>
                <div class="huge">
                  <%= @event.tracks.count %>
                </div>
                <div>
                  <i class="fas fa-layer-group"></i> <%= @event.tracks.count == 1 ? 'Track' : 'Tracks' %>
                </div>
              <% end %>
            </div>

            <div class="mb-3">
              <%= link_to event_sessions_path(@event) do %>
                <div class="huge">
                  <%= @event.sessions.where(approved: true).count %>
                </div>
                <div>
                  <i class="fas fa-clipboard-list"></i> <%= @event.sessions.where(approved: true).count == 1 ? 'Session' : 'Sessions' %>
                </div>
              <% end %>
            </div>

            <% if @event.scheduled || admin? %>
            <div class="mb-3">
            <%= link_to grid_event_sessions_path(@event) do %>
              <div class="huge">
                <i class="fas fa-grip-horizontal"></i>
              </div>
              <div>
                Event Schedule
              </div>
            <% end %>
            </div>
            <% end %>

          </div>
        <% else %>
          <p><em>The schedule &amp; session information for this event has not been published yet. Please check back later!</em></p>
        <% end %>

      </div>
      <% if admin? %>
        <div class="card-footer">
          <%= link_to 'Edit Event', edit_event_path(@event), class: 'btn btn-warning' %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-md-9">
    <div class="card mb-5">
      <div class="card-body">
        <%= @event.description %>
      </div>
    </div>
  </div>
</div>