config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/manage_users' => 'users#all', as: 'users'
  post '/manage_users/:id' => 'users#delete', as: 'delete_user'


  resources :events, path: '/' do
    resources :tracks
    resources :sessions do
      post 'approve', on: :member
      post 'revoke', on: :member
      get 'grid', on: :collection
    end
    resources :users, except: [:delete], path: :presenters do
      get 'master', on: :collection
    end
    resources :pages
    resources :rooms
    resources :slots
    get 'archive', on: :member
    get 'unarchive', on: :member
  end

  root to: 'events#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :track
  belongs_to :room
end

app/models/event.rb
class Event < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  has_rich_text :description
  has_many :pages
  has_many :rooms
  has_many :slots
  has_many :sessions
  has_many :users, through: :sessions
  has_many :tracks

  def unschedule!
    sessions.each do |s|
      s.slots = []
      s.rooms = []
      s.save
    end
  end
end

app/models/page.rb
class Page < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  has_rich_text :content
  belongs_to :event

  scope :publishable, -> { where("title NOT LIKE '_%'") }

  def should_generate_new_friendly_id?
   title_changed?
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_rich_text :description
  belongs_to :event
  has_many :assignments
  has_many :tracks, through: :assignments
  has_and_belongs_to_many :sessions
end

app/models/rooms_sessions.rb
class RoomsSessions < ApplicationRecord
  belongs_to :session
  belongs_to :room
end

app/models/session.rb
class Session < ApplicationRecord
  has_rich_text :description
  has_rich_text :organizer_notes
  has_rich_text :links
  belongs_to :event
  has_and_belongs_to_many :slots
  has_and_belongs_to_many :rooms
  has_and_belongs_to_many :users
  has_many :taggings, dependent: :destroy
  has_many :tracks, through: :taggings

  def to_presenter_info
    "#{title} - #{slots.map(&:name).join('/')} - #{rooms.map(&:name).join('/')}"
  end

  def live?
    approved && slots.any?(&:happening?) && rooms.present?
  end
end

app/models/sessions_slots.rb
class SessionsSlots < ApplicationRecord
  belongs_to :session
  belongs_to :slot
end

app/models/sessions_users.rb
class SessionsUsers < ApplicationRecord
  belongs_to :session
  belongs_to :user
end

app/models/slot.rb
class Slot < ApplicationRecord
  belongs_to :event
  has_and_belongs_to_many :sessions

  def name
    r = ''
    r << starts_at.strftime('%b %e, %l:%M %p - ')
    if starts_at.to_date == ends_at.to_date
      r << ends_at.strftime('%l:%M %p')
    else
      r << ends_at.strftime('%b %e, %l:%M %p - ')
    end
    r
  end

  def happening?
    starts_at <= Time.now && ends_at >= Time.now
  end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :track
  belongs_to :session
end

app/models/track.rb
class Track < ApplicationRecord
  extend FriendlyId
  friendly_id :label, use: :slugged
  has_many :taggings
  has_many :sessions, through: :taggings
  has_many :assignments
  has_many :rooms, through: :assignments
  belongs_to :event
  has_rich_text :description
end

app/models/user.rb
class User < ApplicationRecord
  has_rich_text :profile
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_and_belongs_to_many :sessions

  def admin?
    administrator
  end

  alias :admin :admin?

  def name
    "#{first_name} #{last_name}"
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/presenters_helper.rb
module PresentersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @event.present? ? "#{@event.name}, powered by " : '' %>FINForums</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  </head>

  <body>
    <%= render partial: 'partials/navbar' %>
    <div class="container">
      <%= flash_messages %>
      <%= yield %>
    </div>

    <div class="footer">
      <a href="https://gitlab.com/bkt/finforums">FINForums</a> is an open source project managed by <a href="https://brad-thompson.com">Brad Thompson</a> and hosted by <a href="https://westside-robotics.info">Westside Robotics</a>.
    </div>
    <script>
$(function () {
    $('[data-toggle="popover"]').popover()
    $('[data-toggle="tooltip"]').tooltip()
})
    </script>
  </body>
</html>

app/views/layouts/full.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @event.present? ? "#{@event.name}, powered by " : '' %>FINForums</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  </head>

  <body>
    <%= render partial: 'partials/navbar' %>
    <div class="container-fluid">
      <%= flash_messages %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: [@event, page], local: true) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card">
    <div class="card-body">
      <div class="form-row mb-3">
        <div class="col">
          <%= form.label :title %>
        </div>
        <div class="col">
          <%= form.text_field :title, class: 'form-control' %>
        </div>
      </div>

      <%= form.rich_text_area :content %>

      <div class="form-row mt-3">
        <div class="col">
          <%= form.submit nil, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

app/views/pages/index.html.erb
<h1>Pages</h1>

<div class="card">
  <div class="card-body">
    <div class="row">
    <% @pages.each do |page| %>
      <div class="col">
        <%= link_to page.title, [@event, page] %>
      </div>
    <% end %>
    </div>
  </div>
  <div class="card-footer">
    <%= link_to "Create New Page", new_event_page_path(@event), class: 'btn btn-primary' %>
  </div>
</div>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

app/views/pages/show.html.erb
<h1><%= @page.title %></h1>

<div class="card">
  <div class="card-body">
    <%= @page.content %>
  </div>
  <% if admin? %>
    <div class="card-footer d-flex justify-content-between">
      <%= link_to 'Edit Page', edit_event_page_path(@event, @page), class: 'btn btn-warning' %>
      <%= link_to 'Delete Page', [@event, @page], confirm: 'Are you sure?', method: :delete, class: 'btn btn-danger' %>
    </div>
  <% end %>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">FINForums</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if @event.present? && @event.persisted? %>
        <li class="nav-item">
          <%= link_to @event.name, @event, class: 'nav-link' %>
        </li>
        <% if (@event.published && @event.pages.publishable.present?) || admin? %>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-file"></i> Event Information
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% @event.pages.each do |page| %>
              <%= link_to page.title, [@event, page], class: 'dropdown-item' if page.persisted? && page.title[0] != '_' %>
            <% end %>
            <% if admin? %>
              <div class="dropdown-divider"></div>
              <%= link_to 'Manage Pages', event_pages_path(@event), class: 'dropdown-item' %>
            <% end %>
          </div>
        </li>
      <% end %>

      <% if @event.scheduled || admin? %>
        <li class="nav-item">
          <%= link_to grid_event_sessions_path(@event), class: 'nav-link' do %>
            <i class="fas fa-grip-horizontal"></i> Schedule
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to event_rooms_path(@event), class: 'nav-link' do %>
            <i class="fas fa-door-open"></i> Rooms
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to event_slots_path(@event), class: 'nav-link' do %>
            <i class="fas fa-clock"></i> Slots
          <% end %>
        </li>
      <% end %>
      <% if @event.scheduled || @event.published || admin? %>
        <li class="nav-item">
          <%= link_to event_users_path(@event), class: 'nav-link' do %>
            <i class="fas fa-user"></i> Presenters
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to event_tracks_path(@event), class: 'nav-link' do %>
            <i class="fas fa-layer-group"></i> Tracks
          <% end %>
        </li>
      <% end %>

      <% if (@event.open && current_user) || @event.published || @event.scheduled || admin? %>
        <li class="nav-item">
          <%= link_to event_sessions_path(@event), class: 'nav-link' do %>
            <i class="fas fa-clipboard-list"></i> <%= @event.scheduled || @event.published ? "Sessions" : "Proposals"%>
          <% end %>
        </li>
      <% end %>


      <% else %>
        <li class="nav-item">
          <%= link_to 'Current Events', root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Archived Events', root_path(archived: true), class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
    <ul class="navbar-nav">
      <% if current_user %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.email %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Edit Profile', edit_user_registration_path, class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Log Out', destroy_user_session_path, class: 'dropdown-item', method: :delete %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>

    </ul>
  </div>
</nav>