config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/manage_users' => 'users#all', as: 'users'
  post '/manage_users/:id' => 'users#delete', as: 'delete_user'


  resources :events, path: '/' do
    resources :tracks
    resources :sessions do
      post 'approve', on: :member
      post 'revoke', on: :member
      get 'grid', on: :collection
    end
    resources :users, except: [:delete], path: :presenters do
      get 'master', on: :collection
    end
    resources :pages
    resources :rooms
    resources :slots
    get 'archive', on: :member
    get 'unarchive', on: :member
  end

  root to: 'events#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  has_rich_text :description
  belongs_to :event
  has_many :assignments
  has_many :tracks, through: :assignments
  has_and_belongs_to_many :sessions
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_event
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :check_for_admin, except: [:index, :show]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = @event.rooms.order(:name)
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = @event.rooms.build
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = @event.rooms.build(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to [@event, @room], notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to [@event, @room], notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to event_rooms_url(@event), notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :description, :capacity, :embed_code, track_ids: [])
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: [@event, room], local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card">
    <div class="card-body">
      <div class="form-row mb-3">
        <div class="col-2">
          <%= form.label :name %>
        </div>
        <div class="col-6">
          <%= form.text_field :name, class: 'form-control' %>
        </div>
        <div class="col-2">
          <%= form.label :capacity %>
        </div>
        <div class="col-2">
          <%= form.number_field :capacity, class: 'form-control' %>
        </div>
      </div>

      <div class="form-row mb-3">
        <div class="col-2">
          <%= form.label :embed_code %>
        </div>
        <div class="col-10">
          <%= form.text_field :embed_code, class: 'form-control' %>
        </div>
      </div>

      <%= form.rich_text_area :description %>

      <%= hidden_field_tag 'room[track_ids][]', '' %>
      <% @event.tracks.order(:label).each do |track| %>
        <div class="row">
          <div class="col-1">
            <%= check_box_tag "room[track_ids][]", track.id, @room.tracks.include?(track) %>
          </div>
          <div class="col">
            <%= track_badge(track) %>
          </div>
        </div>
      <% end %>

      <div class="form-row mt-3">
        <div class="col">
          <%= form.submit nil, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

app/views/rooms/index.html.erb
<h1><%= @event.name %> Rooms</h1>

<% if admin? ||@event.pages.where(title: '_rooms').first.content.present? %>
  <div class="card mb-5">
    <div class="card-body">
      <% if p = @event.pages.where(title: '_rooms').first %>
        <%= p.content %>
      <% end %>
    </div>
    <% if admin? %>
      <div class="card-footer">
        <%= link_to 'Add a New Room', new_event_room_path(@event), class: 'btn btn-primary' %>
        <% if p = @event.pages.where(title: '_rooms').first %>
          <%= link_to 'Edit Content Page', edit_event_page_path(@event, p), class: 'btn btn-warning' %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

<div class="card">
  <div class="card-body">
    <% @rooms.each do |room| %>
      <div class="row mb-4">
        <div class="col">
          <%= link_to room.name, [@event, room] %>
          <% if room.tracks.present? %>
            <div>
              <% room.tracks.each do |track| %>
                <%= track_badge track %>
              <% end %>
            </div>
          <% end %>
          <%= room.description %>
        </div>
        <div class="col">
          <% room.sessions.where(approved: true).each do |session| %>
            <div>
              <%= link_to session.title, [@event, session] %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

app/views/rooms/show.html.erb
<h1><%= @room.name %></h1>

<div class="row">
  <div class="col-md-4">
    <div class="card">
      <div class="card-body">
        <% if @room.tracks.present? %>
          <div>
            <% @room.tracks.each do |track| %>
              <%= track_badge track %>
            <% end %>
          </div>
        <% end %>
        <%= @room.description %>
      </div>
      <% if admin? %>
        <div class="card-footer d-flex justify-content-between">
          <%= link_to 'Edit Room', edit_event_room_path(@event, @room), class: 'btn btn-warning' %>
          <%= link_to 'Delete Room', [@event, @room], confirm: 'Are you sure?', method: :delete, class: 'btn btn-danger' %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-md-8">
    <% if @room.embed_code.present? %>
      <div class="card dontexpand mb-3">
        <div class="card-body">
          <%= @room.embed_code.html_safe %>
        </div>
      </div>
    <% end %>
    <div class="card dontexpand">
      <div class="card-body">
        <% @room.sessions.each do |session| %>
          <div class="row align-items-center mb-2">
            <div class="col">
              <%= link_to session.title, [@event, session] %>
            </div>
            <div class="col">
              <% session.users.each do |user| %>
                <div><%= link_to user.name, event_user_path(@event, user) %></div>
              <% end %>
              <% session.slots.each do |slot| %>
                <div>
                  <%= link_to slot.name, [@event, slot] %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>